### PR TITLE
Added jump lists

### PR DESCRIPTION
**Pull request by lorenzofar**
Added jump lists to the app (only if supported)

### CODE REVIEW

**Comment by lorenzofar** [comment]
Fixed Issue #573

**Comment by NPadrutt** [comment]
mh, I still can't resolve Jumplist and Windows.UI.StartScreen is unused. I have the 10586 sdk installed. what do I miss? o.O

**Comment by lorenzofar** [comment]
Does the target sdk of the project is the 10.0.10586 ?

**Comment by lorenzofar** [comment]
Can you share a screenshot?

**Comment by NPadrutt** [comment]
ah, I reinstalled the sdk. Now it works.

**Comment by lorenzofar** [comment]
Great!

**Pull request merged**
